### ISSUE TITLE
Players get revived in spec

### ISSUE THREAD

**Issue by Derphammer** [Starblaster64/Vs-Saxton-Hale-2#79] opened 2018-08-04 23:49 UTC
So if a player tries to go spec they get revived back on red kinda a strange bug but i also noticed that it can be abused after someone dies they can go spec and it can revive them again.

**Comment by Derphammer** [comment] 2018-08-04 23:50
i think it may have something to do with plague doctor not really sure yet.

**Comment by kevyonan** [comment] 2018-08-05 00:51
that bug is not able to be fixed without alot of checking because that's an Arena bug within TF2.
The bug only happens if someone goes spectator and hasn't joined a team and class yet. Doing so allows you to join in the middle of the round.

This is something to bring up to Valve.

**Comment by kevyonan** [comment] 2018-08-05 13:59
ok, I think I see what the issue is you're talking about.

**Comment by kevyonan** [comment] 2018-08-05 15:21
I believe I have a fix ready, it's an issue in the player respawn event. I will throw in a patch.

**Comment by kevyonan** [comment] 2018-08-13 00:34
@Derphammer Plugin's been updated, have u still been having this glitch?

**Closed as completed** 2018-08-13 00:56 UTC
Labels: type: bug, status: ready
